experiment:
  name: blis-1-llama-3-1-8b-instruct
  description: 'Saturation Exp #1: Llama-3.1-8B-Instruct BF16 TP1 on H100'
stack:
  treatments:
    tensorParallelism:
    - 1
    dataLocalParallelism:
    - 1
  MAX_MODEL_LEN: 8192
  MAX_NUM_BATCHED_TOKENS: 2048
  MAX_NUM_SEQS: 128
  BLOCK_SIZE: 16
  extra_overrides:
  - decode.containers[name="vllm"].args=--scheduling-policy=priority
  model:
    helmValues:
      fullnameOverride: FULLNAME
      serviceAccountOverride: default
      multinode: false
      modelArtifacts:
        uri: pvc://model-pvc/models/MODEL
        size: 300Gi
        authSecretName: hf-secret
        name: MODEL
        labels:
          llm-d.ai/inferenceServing: 'true'
          llm-d.ai/model: FULLNAME
      routing:
        servicePort: 8000
        proxy:
          enabled: false
      prefill:
        create: false
      decode:
        create: true
        replicas: 1
        acceleratorTypes:
          labelKey: nvidia.com/gpu.product
          labelValues:
          - NVIDIA-H100-80GB-HBM3
        containers:
        - name: vllm
          env:
          - name: VLLM_CONFIGURE_LOGGING
            value: '1'
          - name: VLLM_LOGGING_CONFIG_PATH
            value: /workspace/vllm_logging.json
          - name: HF_HOME
            value: /mnt/exp/.cache/huggingface
          - name: TRANSFORMERS_CACHE
            value: /mnt/exp/.cache/huggingface
          mountModelVolume: true
          image: vllm/vllm-openai:v0.19.1
          modelCommand: vllmServe
          resources:
            limits:
              memory: 128Gi
              cpu: '32'
            requests:
              memory: 128Gi
              cpu: '32'
          extraConfig:
            startupProbe:
              httpGet:
                path: /health
                port: 8000
              failureThreshold: 60
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 5
            livenessProbe:
              tcpSocket:
                port: 8000
              failureThreshold: 3
              periodSeconds: 5
            readinessProbe:
              httpGet:
                path: /health
                port: 8000
              failureThreshold: 3
              periodSeconds: 5
          volumeMounts:
          - name: data
            mountPath: /mnt/exp
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        annotations:
          gpu-reaper.io/exclude: 'true'
  cpu_offload: false
  kv_offloading_size: 0
orc:
  latency_model: trained-physics
  gpu_type: H100
workload:
  harness: orc
  orcSpec:
    version: '2'
    seed: 42
    category: ''
    clients: []
    cohorts:
    - id: afternoon-background
      population: 1
      slo_class: background
      arrival:
        process: poisson
      input_distribution:
        type: lognormal
        params:
          mu: 6.69621191290237
          sigma: 0.5902513998220089
      output_distribution:
        type: lognormal
        params:
          mu: 4.114017268596266
          sigma: 0.908969534506003
      streaming: true
      rate_fraction: 1
      spike:
        start_time_us: 0
        duration_us: 600000000
        trace_rate: 12.406919642857135
    - id: afternoon-batch
      population: 1
      slo_class: batch
      arrival:
        process: poisson
      input_distribution:
        type: lognormal
        params:
          mu: 6.607780910378171
          sigma: 0.8727319577006727
      output_distribution:
        type: lognormal
        params:
          mu: 4.096106531698332
          sigma: 1.2519617625757922
      streaming: true
      rate_fraction: 1
      spike:
        start_time_us: 0
        duration_us: 600000000
        trace_rate: 12.406919642857135
    - id: afternoon-critical
      population: 1
      slo_class: critical
      arrival:
        process: poisson
      input_distribution:
        type: lognormal
        params:
          mu: 6.582734044244264
          sigma: 0.5629375545724375
      output_distribution:
        type: lognormal
        params:
          mu: 4.624020180084728
          sigma: 0.8848836416915962
      streaming: true
      rate_fraction: 1
      spike:
        start_time_us: 0
        duration_us: 600000000
        trace_rate: 12.406919642857135
    - id: afternoon-sheddable
      population: 1
      slo_class: sheddable
      arrival:
        process: poisson
      input_distribution:
        type: lognormal
        params:
          mu: 6.4993704071213605
          sigma: 0.6893972829089396
      output_distribution:
        type: lognormal
        params:
          mu: 4.069653546012583
          sigma: 0.9474746650875042
      streaming: true
      rate_fraction: 1
      spike:
        start_time_us: 0
        duration_us: 600000000
        trace_rate: 12.406919642857135
    - id: afternoon-standard
      population: 1
      slo_class: standard
      arrival:
        process: poisson
      input_distribution:
        type: lognormal
        params:
          mu: 6.813289322036138
          sigma: 0.7095809961919253
      output_distribution:
        type: lognormal
        params:
          mu: 3.8889842819443703
          sigma: 0.928382494594449
      streaming: true
      rate_fraction: 1
      spike:
        start_time_us: 0
        duration_us: 600000000
        trace_rate: 12.406919642857135
    aggregate_rate: 0
  horizon: 600
  detectSaturation: 'true'
upload_target:
  type: s3
  configuration:
    bucket: cloud-object-storage-cos-standard-ere
    endpoint: https://s3.us-east.cloud-object-storage.appdomain.cloud
