apiVersion: v1
kind: Pod
metadata:
  name: pvc-debugger
  namespace: diya
spec:
  containers:
    - name: shell
      image: python:3.11-slim
      command: ['bash', '-c']
      args: ["sleep infinity"]
      volumeMounts:
        - name: model-storage
          mountPath: /mnt
      securityContext:
        runAsUser: 0
  volumes:
    - name: model-storage
      persistentVolumeClaim:
        claimName: data-pvc
  restartPolicy: Never