apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: blis-41-llama-3-1-8b-general
spec:
  description: Exp
  workspaces:
  - name: model-cache
    description: Location where models are stored; shared by multiple model servers
  - name: hf-credentials
    description: Secret workspace containing a HuggingFace token
  - name: data
    description: Cache of results and harness installation
  - name: target-credentials
    description: Secret workspace containing upload target credentials. For example, AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY for s3.
  params:
  - name: experimentId
    type: string
    description: Identifier for experiment execution
  - name: model
    type: string
    description: the model to be deployed
  - name: namespace
    type: string
    description: Kubernetes namespace where workload will execute
  tasks:
  - name: download-model
    taskRef:
      name: download-model
    workspaces:
    - name: model-cache
    - name: hf-credentials
    params:
    - name: model
      value: $(params.model)
  - name: install-inference-perf
    taskRef:
      name: install-inference-perf-blis
    runAfter:
    - download-model
    workspaces:
    - name: data
  - name: create-exp-config-1
    taskRef:
      name: create-exp-config
    runAfter:
    - install-inference-perf
    workspaces:
    - name: data
    params:
    - name: model
      value: $(params.model)
    - name: tp
      value: '1'
    - name: max_model_len
      value: '4096'
    - name: max_num_batched_tokens
      value: '2048'
    - name: max_num_seqs
      value: '128'
    - name: app
      value: inference-perf
    - name: results_dir
      value: $(params.experimentId)-1
  - name: deploy-model-1
    description: Deploy model engines. Uses the modelservice helm chart. The task implementation automatically overrides "modelArtifacts.name", "modelArtifacts.uri" "modelArtifacts.labels."llm-d.ai/model", and "fullnameOverride" to avoid conflicts and ensure consistency.
    taskRef:
      name: deploy-model
    runAfter:
    - install-inference-perf
    workspaces:
    - name: model-cache
    params:
    - name: model
      value: $(params.model)
    - name: modelLabel
      value: $(params.experimentId)-1
    - name: namespace
      value: $(params.namespace)
    - name: config
      value:
        fullnameOverride: FULLNAME
        serviceAccountOverride: default
        multinode: false
        modelArtifacts:
          uri: pvc://model-pvc/models/MODEL
          size: 300Gi
          authSecretName: hf-secret
          name: MODEL
          labels:
            llm-d.ai/inferenceServing: 'true'
            llm-d.ai/model: FULLNAME
        routing:
          servicePort: 8000
          proxy:
            enabled: false
        prefill:
          create: false
        decode:
          create: true
          replicas: 1
          acceleratorTypes:
            labelKey: nvidia.com/gpu.product
            labelValues:
            - NVIDIA-A100-SXM4-80GB
          parallelism:
            data: 1
            tensor: 1
          containers:
          - name: vllm
            env:
            - name: VLLM_CONFIGURE_LOGGING
              value: '1'
            - name: VLLM_LOGGING_CONFIG_PATH
              value: /workspace/vllm_logging.json
            - name: HF_HOME
              value: /mnt/exp/.cache/huggingface
            - name: TRANSFORMERS_CACHE
              value: /mnt/exp/.cache/huggingface
            mountModelVolume: true
            image: vllm/vllm-openai:v0.15.1
            modelCommand: vllmServe
            resources:
              limits:
                memory: 128Gi
                cpu: '32'
              requests:
                memory: 128Gi
                cpu: '32'
            extraConfig:
              startupProbe:
                httpGet:
                  path: /health
                  port: 8000
                failureThreshold: 60
                initialDelaySeconds: 30
                periodSeconds: 30
                timeoutSeconds: 5
              livenessProbe:
                tcpSocket:
                  port: 8000
                failureThreshold: 3
                periodSeconds: 5
              readinessProbe:
                httpGet:
                  path: /health
                  port: 8000
                failureThreshold: 3
                periodSeconds: 5
            volumeMounts:
            - name: data
              mountPath: /mnt/exp
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: data-pvc
          annotations:
            gpu-reaper.io/exclude: 'true'
    - name: overrides
      value:
      - decode.parallelism.tensor=1
      - decode.containers[name="vllm"].args=--max-model-len=4096
      - decode.containers[name="vllm"].args=--max-num-batched-tokens=2048
      - decode.containers[name="vllm"].args=--max-num-seqs=128
      - decode.containers[name="vllm"].env[name="VLLM_LOGGING_CONFIG_PATH"].value="/mnt/exp/$(params.experimentId)-1/vllm_logging.json"
  - name: run-workload-1
    description: Run workload against model server using inference-perf.
    taskRef:
      name: run-workload-inference-perf-blis
    runAfter:
    - deploy-model-1
    timeout: 350m
    retries: 3
    workspaces:
    - name: data
    - name: hf-credentials
    params:
    - name: model
      value: $(params.model)
    - name: modelLabel
      value: $(params.experimentId)-1
    - name: results_dir
      value: $(params.experimentId)-1
    - name: profileTemplate
      value:
        load:
          type: constant
          stages:
          - rate: 8.0
            duration: 600
          - rate: 20.0
            duration: 600
        api:
          type: completion
          streaming: true
        server:
          type: vllm
          model_name: MODEL
          base_url: STACK_ENDPOINT
          ignore_eos: true
        tokenizer:
          pretrained_model_name_or_path: TOKENIZER
        data:
          type: shared_prefix
          shared_prefix:
            num_unique_system_prompts: 9
            num_users_per_system_prompt: 5
            system_prompt_len: 100
            question_len: 447
            output_len: 248
            enable_multi_turn_chat: true
        report:
          request_lifecycle:
            summary: true
            per_stage: true
            per_request: true
        storage:
          local_storage:
            path: PATH
  - name: delete-model-1
    description: Delete the model engine.
    runAfter:
    - run-workload-1
    taskRef:
      name: delete-model
    params:
    - name: namespace
      value: $(params.namespace)
    - name: modelLabel
      value: $(params.experimentId)-1
  - name: raw-upload-1
    description: Upload raw data to target data repository
    taskRef:
      name: upload-s3
    runAfter:
    - run-workload-1
    workspaces:
    - name: data
    - name: target-credentials
    params:
    - name: archive
      value: $(params.experimentId)-1-raw.tar.gz
    - name: paths
      value: '$(params.experimentId)-1

        '
    - name: target
      value:
        bucket: cloud-object-storage-cos-standard-ere
        endpoint: https://s3.us-east.cloud-object-storage.appdomain.cloud
  finally:
  - name: finally-delete-model-1
    taskRef:
      name: delete-model
    params:
    - name: namespace
      value: $(params.namespace)
    - name: modelLabel
      value: $(params.experimentId)-1
