namespace: "diya"

H100:
  context: "diya/api-pokprod001-ete14-res-ibm-com:6443/dipanwita.guhathakurta3@ibm.com"
  gpu_label_key: "nvidia.com/gpu.product"
  gpu_label_value: "NVIDIA-H100-80GB-HBM3"

A100-80GB:
  context: "diya/api-fmaas-vllm-d-fmaas-res-ibm-com:6443/dipanwita.guhathakurta3@ibm.com"
  gpu_label_key: "nvidia.com/gpu.product"
  gpu_label_value: "NVIDIA-A100-SXM4-80GB"

L40S:
  context: "diya/api-fmaas-platform-eval-fmaas-res-ibm-com:6443/dipanwita.guhathakurta3@ibm.com"
  gpu_label_key: "nvidia.com/gpu.product"
  gpu_label_value: "NVIDIA-L40S"
