apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cal-h100-
spec:
  timeouts:
    pipeline: 4h
    tasks: 3h30m
  pipelineRef:
    name: cal-h100
  params:
    - name: namespace
      value: diya
  workspaces:
    - name: model-cache
      persistentVolumeClaim:
        claimName: model-pvc
    - name: hf-credentials
      secret:
        secretName: hf-secret
    - name: data
      persistentVolumeClaim:
        claimName: data-pvc
  taskRunTemplate:
    serviceAccountName: helm-installer
