apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: __PIPELINE_RUN_NAME__
spec:
  timeouts:
    pipeline: 6h
    tasks: 5h30m
  taskRunTemplate:
    serviceAccountName: helm-installer
  workspaces:
    - name: model-cache
      persistentVolumeClaim:
        claimName: model-pvc
    - name: data
      persistentVolumeClaim:
        claimName: data-pvc
    - name: hf-credentials
      secret:
        secretName: hf-secret
        items:
          - key: HF_TOKEN
            path: HF_TOKEN
    - name: target-credentials
      secret:
        secretName: s3-secret
        items:
          - key: AWS_ACCESS_KEY_ID
            path: AWS_ACCESS_KEY_ID
          - key: AWS_SECRET_ACCESS_KEY
            path: AWS_SECRET_ACCESS_KEY
  pipelineRef:
    name: blis-30-mixtral-8x7b-general
  params:
    - { name: experimentId, value: "30-Mixtral-8x7B-tp2-general" }
    - { name: model, value: "mistralai/Mixtral-8x7B-v0.1" }
    - { name: namespace, value: "diya" }
