apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: blis-rh-train
spec:
  description: Training pipeline for BLIS scenario 6
  workspaces:
  - name: data
    description: Cache of training results
  - name: target-credentials
    description: Secret workspace containing upload target credentials.  For example, AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY for s3.
  params:
  - name: experimentId
    type: string
    description: Identifier for experiment execution
  - name: namespace
    type: string
    description: Kubernetes namespace where training will execute
  - name: num_iter
    type: string
    description: Number of BLIS training iterations
  tasks:
  - name: train-blis-rh-0
    taskRef:
      name: train-blis-rh
    workspaces:
    - name: data
    params:
    - name: LLM_NAME
      value: ibm-granite/granite-3.1-8b-instruct
    - name: TP
      value: '1'
    - name: GPU_TYPE
      value: H100
    - name: VLLM_VERSION
      value: vllm/vllm-openai:v0.8.4
    - name: TRAINING_FILEPATH
      value: blis_rh_final.xlsx
    - name: num_iter
      value: $(params.num_iter)
    - name: results_dir
      value: variation-ibm-granite-granite-3-1-8b-instruct-1-H100-vllm-vllm-openai-v0-8-4
  - name: train-blis-rh-1
    taskRef:
      name: train-blis-rh
    workspaces:
    - name: data
    params:
    - name: LLM_NAME
      value: ibm-granite/granite-3.1-8b-instruct
    - name: TP
      value: '2'
    - name: GPU_TYPE
      value: H100
    - name: VLLM_VERSION
      value: vllm/vllm-openai:v0.8.4
    - name: TRAINING_FILEPATH
      value: blis_rh_final.xlsx
    - name: num_iter
      value: $(params.num_iter)
    - name: results_dir
      value: variation-ibm-granite-granite-3-1-8b-instruct-2-H100-vllm-vllm-openai-v0-8-4
  - name: train-blis-rh-2
    taskRef:
      name: train-blis-rh
    workspaces:
    - name: data
    params:
    - name: LLM_NAME
      value: ibm-granite/granite-3.1-8b-instruct
    - name: TP
      value: '4'
    - name: GPU_TYPE
      value: H100
    - name: VLLM_VERSION
      value: vllm/vllm-openai:v0.8.4
    - name: TRAINING_FILEPATH
      value: blis_rh_final.xlsx
    - name: num_iter
      value: $(params.num_iter)
    - name: results_dir
      value: variation-ibm-granite-granite-3-1-8b-instruct-4-H100-vllm-vllm-openai-v0-8-4
  - name: train-blis-rh-3
    taskRef:
      name: train-blis-rh
    workspaces:
    - name: data
    params:
    - name: LLM_NAME
      value: ibm-granite/granite-3.1-8b-instruct
    - name: TP
      value: '1'
    - name: GPU_TYPE
      value: A100-80
    - name: VLLM_VERSION
      value: vllm/vllm-openai:v0.8.4
    - name: TRAINING_FILEPATH
      value: blis_rh_final.xlsx
    - name: num_iter
      value: $(params.num_iter)
    - name: results_dir
      value: variation-ibm-granite-granite-3-1-8b-instruct-1-A100-80-vllm-vllm-openai-v0-8-4
  - name: train-blis-rh-4
    taskRef:
      name: train-blis-rh
    workspaces:
    - name: data
    params:
    - name: LLM_NAME
      value: ibm-granite/granite-3.1-8b-instruct
    - name: TP
      value: '2'
    - name: GPU_TYPE
      value: A100-80
    - name: VLLM_VERSION
      value: vllm/vllm-openai:v0.8.4
    - name: TRAINING_FILEPATH
      value: blis_rh_final.xlsx
    - name: num_iter
      value: $(params.num_iter)
    - name: results_dir
      value: variation-ibm-granite-granite-3-1-8b-instruct-2-A100-80-vllm-vllm-openai-v0-8-4
  - name: train-blis-rh-5
    taskRef:
      name: train-blis-rh
    workspaces:
    - name: data
    params:
    - name: LLM_NAME
      value: meta-llama/llama-3.1-8b-instruct
    - name: TP
      value: '1'
    - name: GPU_TYPE
      value: H100
    - name: VLLM_VERSION
      value: vllm/vllm-openai:v0.8.4
    - name: TRAINING_FILEPATH
      value: blis_rh_final.xlsx
    - name: num_iter
      value: $(params.num_iter)
    - name: results_dir
      value: variation-meta-llama-llama-3-1-8b-instruct-1-H100-vllm-vllm-openai-v0-8-4
  - name: train-blis-rh-6
    taskRef:
      name: train-blis-rh
    workspaces:
    - name: data
    params:
    - name: LLM_NAME
      value: meta-llama/llama-3.1-8b-instruct
    - name: TP
      value: '2'
    - name: GPU_TYPE
      value: H100
    - name: VLLM_VERSION
      value: vllm/vllm-openai:v0.8.4
    - name: TRAINING_FILEPATH
      value: blis_rh_final.xlsx
    - name: num_iter
      value: $(params.num_iter)
    - name: results_dir
      value: variation-meta-llama-llama-3-1-8b-instruct-2-H100-vllm-vllm-openai-v0-8-4
  - name: train-blis-rh-7
    taskRef:
      name: train-blis-rh
    workspaces:
    - name: data
    params:
    - name: LLM_NAME
      value: meta-llama/llama-3.1-8b-instruct
    - name: TP
      value: '4'
    - name: GPU_TYPE
      value: H100
    - name: VLLM_VERSION
      value: vllm/vllm-openai:v0.8.4
    - name: TRAINING_FILEPATH
      value: blis_rh_final.xlsx
    - name: num_iter
      value: $(params.num_iter)
    - name: results_dir
      value: variation-meta-llama-llama-3-1-8b-instruct-4-H100-vllm-vllm-openai-v0-8-4
  - name: train-blis-rh-8
    taskRef:
      name: train-blis-rh
    workspaces:
    - name: data
    params:
    - name: LLM_NAME
      value: meta-llama/llama-3.1-8b-instruct
    - name: TP
      value: '1'
    - name: GPU_TYPE
      value: A100-80
    - name: VLLM_VERSION
      value: vllm/vllm-openai:v0.8.4
    - name: TRAINING_FILEPATH
      value: blis_rh_final.xlsx
    - name: num_iter
      value: $(params.num_iter)
    - name: results_dir
      value: variation-meta-llama-llama-3-1-8b-instruct-1-A100-80-vllm-vllm-openai-v0-8-4
  - name: train-blis-rh-9
    taskRef:
      name: train-blis-rh
    workspaces:
    - name: data
    params:
    - name: LLM_NAME
      value: meta-llama/llama-3.1-8b-instruct
    - name: TP
      value: '2'
    - name: GPU_TYPE
      value: A100-80
    - name: VLLM_VERSION
      value: vllm/vllm-openai:v0.8.4
    - name: TRAINING_FILEPATH
      value: blis_rh_final.xlsx
    - name: num_iter
      value: $(params.num_iter)
    - name: results_dir
      value: variation-meta-llama-llama-3-1-8b-instruct-2-A100-80-vllm-vllm-openai-v0-8-4
  - name: train-blis-rh-10
    taskRef:
      name: train-blis-rh
    workspaces:
    - name: data
    params:
    - name: LLM_NAME
      value: meta-llama/llama-3.1-8b-instruct
    - name: TP
      value: '4'
    - name: GPU_TYPE
      value: A100-80
    - name: VLLM_VERSION
      value: vllm/vllm-openai:v0.8.4
    - name: TRAINING_FILEPATH
      value: blis_rh_final.xlsx
    - name: num_iter
      value: $(params.num_iter)
    - name: results_dir
      value: variation-meta-llama-llama-3-1-8b-instruct-4-A100-80-vllm-vllm-openai-v0-8-4
  - name: train-blis-rh-11
    taskRef:
      name: train-blis-rh
    workspaces:
    - name: data
    params:
    - name: LLM_NAME
      value: qwen/qwen2.5-7b-instruct
    - name: TP
      value: '1'
    - name: GPU_TYPE
      value: H100
    - name: VLLM_VERSION
      value: vllm/vllm-openai:v0.8.4
    - name: TRAINING_FILEPATH
      value: blis_rh_final.xlsx
    - name: num_iter
      value: $(params.num_iter)
    - name: results_dir
      value: variation-qwen-qwen2-5-7b-instruct-1-H100-vllm-vllm-openai-v0-8-4
  - name: train-blis-rh-12
    taskRef:
      name: train-blis-rh
    workspaces:
    - name: data
    params:
    - name: LLM_NAME
      value: qwen/qwen2.5-7b-instruct
    - name: TP
      value: '2'
    - name: GPU_TYPE
      value: H100
    - name: VLLM_VERSION
      value: vllm/vllm-openai:v0.8.4
    - name: TRAINING_FILEPATH
      value: blis_rh_final.xlsx
    - name: num_iter
      value: $(params.num_iter)
    - name: results_dir
      value: variation-qwen-qwen2-5-7b-instruct-2-H100-vllm-vllm-openai-v0-8-4
  - name: train-blis-rh-13
    taskRef:
      name: train-blis-rh
    workspaces:
    - name: data
    params:
    - name: LLM_NAME
      value: qwen/qwen2.5-7b-instruct
    - name: TP
      value: '4'
    - name: GPU_TYPE
      value: H100
    - name: VLLM_VERSION
      value: vllm/vllm-openai:v0.8.4
    - name: TRAINING_FILEPATH
      value: blis_rh_final.xlsx
    - name: num_iter
      value: $(params.num_iter)
    - name: results_dir
      value: variation-qwen-qwen2-5-7b-instruct-4-H100-vllm-vllm-openai-v0-8-4
  - name: train-blis-rh-14
    taskRef:
      name: train-blis-rh
    workspaces:
    - name: data
    params:
    - name: LLM_NAME
      value: qwen/qwen2.5-7b-instruct
    - name: TP
      value: '1'
    - name: GPU_TYPE
      value: A100-80
    - name: VLLM_VERSION
      value: vllm/vllm-openai:v0.8.4
    - name: TRAINING_FILEPATH
      value: blis_rh_final.xlsx
    - name: num_iter
      value: $(params.num_iter)
    - name: results_dir
      value: variation-qwen-qwen2-5-7b-instruct-1-A100-80-vllm-vllm-openai-v0-8-4
  - name: train-blis-rh-15
    taskRef:
      name: train-blis-rh
    workspaces:
    - name: data
    params:
    - name: LLM_NAME
      value: qwen/qwen2.5-7b-instruct
    - name: TP
      value: '2'
    - name: GPU_TYPE
      value: A100-80
    - name: VLLM_VERSION
      value: vllm/vllm-openai:v0.8.4
    - name: TRAINING_FILEPATH
      value: blis_rh_final.xlsx
    - name: num_iter
      value: $(params.num_iter)
    - name: results_dir
      value: variation-qwen-qwen2-5-7b-instruct-2-A100-80-vllm-vllm-openai-v0-8-4
  - name: train-blis-rh-16
    taskRef:
      name: train-blis-rh
    workspaces:
    - name: data
    params:
    - name: LLM_NAME
      value: qwen/qwen2.5-7b-instruct
    - name: TP
      value: '4'
    - name: GPU_TYPE
      value: A100-80
    - name: VLLM_VERSION
      value: vllm/vllm-openai:v0.8.4
    - name: TRAINING_FILEPATH
      value: blis_rh_final.xlsx
    - name: num_iter
      value: $(params.num_iter)
    - name: results_dir
      value: variation-qwen-qwen2-5-7b-instruct-4-A100-80-vllm-vllm-openai-v0-8-4
